services:
  reverse_proxy:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - frontend
      - backend
    depends_on:
      - web1
      - web2
      - web3

  web1:
    image: nginx:alpine
    volumes:
      - ./web_1_myweb:/usr/share/nginx/html
    networks:
      - backend

  web2:
    image: nginx:alpine
    volumes:
      - ./web_2_myresearch:/usr/share/nginx/html
      - ./web_1_myweb/bootstrap-5.2.3:/usr/share/nginx/html/bootstrap-5.2.3
      - ./web_1_myweb/styles.css:/usr/share/nginx/html/styles.css
      # - ./web_1_myweb/index.html:/usr/share/nginx/html/index.html
    networks:
      - backend
    depends_on:
      - web1

  web3:
    image: nginx:alpine
    volumes:
      - ./web_3_ct519:/usr/share/nginx/html
      - ./web_1_myweb/bootstrap-5.2.3:/usr/share/nginx/html/bootstrap-5.2.3
      - ./web_1_myweb/styles.css:/usr/share/nginx/html/styles.css
      # - ./web_1_myweb/index.html:/usr/share/nginx/html/index.html
    networks:
      - backend
    depends_on:
      - web2
  
networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge



    #   - web1
    #   - web2
    #   - web3